### ISSUE TITLE
Completed: kracken-good-accessibility 

### ISSUE THREAD

**Issue by haywasta** [haywasta/kraken-good-accessibility#1]
@thatkidmadrid

I completed the kracken-good-accessibility assignment, but I could not submit it through Markbot because of the screenshot loading issues. Could you please check over the assignment for me? Thank you!

Stacey Johsntone
Group 020

**Comment by thatkidmadrid** [comment]
Great!

I think overall it's well done, and you're demonstrating that you understand how the aria roles should be used.

The descriptions and alternate labels make sense, but the one nit-pick is the order in which the landmarks appear in the voiceover rotor. This is because you have the `role="main"` on your main tag, which is usually the case and typically fine.  If you moved it to the `div` inside the `main`, after the navigation header, it may make more sense to the voiceover user, but this is a decision that the designer can make. No need to change this, but understand why I'm bringing it up :)

I'm adding the grade to your LTW now (also thanks for including the group number! that makes my life a little bit easier)
